name: dart_bs58check
description: A straight forward implementation of base58check extending upon base58.
version: 2.0.0
homepage: https://github.com/dart-bitcoin-lib/dart-bs58check
repository: https://github.com/dart-bitcoin-lib/dart-bs58check
issue_tracker: https://github.com/dart-bitcoin-lib/dart-bs58check/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.3.4
  convert: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
